version: '3.6'
services:
  master-1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: redis-master-1
    command: redis-server /etc/redis/redis.conf
    network_mode: host
    ports:
      - 6379:6379
      - 16379:16379
    volumes:
      - /Users/joker/go/src/examples/redis-docker/docker_redis_cluster/master1/redis.conf:/etc/redis/redis.conf
  master-2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: redis-master-2
    command: redis-server /etc/redis/redis.conf
    network_mode: host
    ports:
      - 6380:6380
      - 16380:16380
    volumes:
      - /Users/joker/go/src/examples/redis-docker/docker_redis_cluster/master2/redis.conf:/etc/redis/redis.conf
  master-3:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: redis-master-3
    command: redis-server /etc/redis/redis.conf
    network_mode: host
    ports:
      - 6381:6381
      - 16381:16381
    volumes:
      - /Users/joker/go/src/examples/redis-docker/docker_redis_cluster/master3/redis.conf:/etc/redis/redis.conf
  slave-1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: redis-slave-1
    command: redis-server /etc/redis/redis.conf
    network_mode: host
    ports:
      - 7379:7379
      - 17379:17379
    volumes:
      - /Users/joker/go/src/examples/redis-docker/docker_redis_cluster/slave1/redis.conf:/etc/redis/redis.conf
  slave-2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: redis-slave-2
    command: redis-server /etc/redis/redis.conf
    network_mode: host
    ports:
      - 7380:7380
      - 17380:17380
    volumes:
      - /Users/joker/go/src/examples/redis-docker/docker_redis_cluster/slave2/redis.conf:/etc/redis/redis.conf
  slave-3:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: redis-slave-3
    command: redis-server /etc/redis/redis.conf
    network_mode: host
    ports:
      - 7381:7381
      - 17381:17381
    volumes:
      - /Users/joker/go/src/examples/redis-docker/docker_redis_cluster/slave3/redis.conf:/etc/redis/redis.conf

