
OrdererOrgs:
  - Name: Orderer
    Domain: demo.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer0
      - Hostname: orderer2
      - Hostname: orderer3
      - Hostname: orderer4
      - Hostname: orderer5

PeerOrgs:
  - Name: Org1
    Domain: org1.demo.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1
  - Name: Org2
    Domain: org2.demo.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1
