goPath: /Users/joker/go
cryptVersion: 1
configPath: /Users/joker/go/src/vlink.com/v2/vlink-rpc/resources/blockchain-config-local.yaml
channels:
  - channelId: userchannel
    needListOnBlockEvent: true
    channelConfigPath: /Users/joker/go/src/vlink.com/v2/vlink-blockchain-network-raft/artifacts/userchannel.tx
    orders:
      - ordererId: orderer0.vlink.link
        ordererAddress: orderer0.vlink.link
        ordererPort: 5050
    organizations:
      - organizationId: VlinkOrgMSP
        users:
          - userName: 'User1'
            admin: false
          - userName: 'Admin'
            admin: true
        peer:
          endorserPeers:
            - address: user0.peer.vlink.link
              port: 11051
              chainCodes:
                - chainCodeId: usercc
                  chainCodePath: vlink.com/v2/vlink-chaincodes/usercc
                  needUpdate: false
        ca:
          caName: 'org.ca.vlink.link'
  - channelId: copyrightchannel
    needListOnBlockEvent: true
    channelConfigPath: /Users/joker/go/src/vlink.com/v2/vlink-blockchain-network-raft/artifacts/copyrightchannel.tx
    orders:
      - ordererId: orderer0.vlink.link
        ordererAddress: orderer0.vlink.link
        ordererPort: 5050
    organizations:
      - organizationId: VlinkOrgMSP
        users:
          - userName: 'User1'
            admin: false
          - userName: 'Admin'
            admin: true
        peer:
          endorserPeers:
            - address: copyright0.peer.vlink.link
              port: 12051
              chainCodes:
                - chainCodeId: copyrightcc
                  chainCodePath: vlink.com/v2/vlink-chaincodes/copyrightcc
                  needUpdate: false
        ca:
          caName: 'org.ca.vlink.link'
